### PR TITLE
Remove netlify config since webapp is published in an image now

### PR DESCRIPTION
**Pull request by davidvandusen**
## Proposed changes

In simplifying the deployment, the webapp is published in an image that is run on the Docker stack now, so there's no need for any of the Netlify config. The Netlify site that previously hosted the webapp has been deleted.

Just another step in #90.

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

### CODE REVIEW

**Review by pthan1 — APPROVED** [review]
What'll be the next step to address issue #90 now that netlify is no longer being used?

**Comment by davidvandusen** [comment]
@pthan1 The next step is to containerize the Flyway migrations. Currently they're done manually on prod.

**Review by eileenxue — APPROVED** [review]

**Comment by eileenxue** [comment]
If you were to create another web app now, would you set up everything in Docker from the beginning?

**Comment by davidvandusen** [comment]
@eileenxue It was always the case that we wanted to have deployments be fully containerized. The reason it's not set up that way now is because of externalities like timelines and budgets and other unknown unknowns.

The way priorities panned out, it was better to do the simplest thing to ship the software (that is, take on tech debt) and then invest time in doing things a better way when time is available (that is, repay the debt).

**Pull request merged**
