### PR TITLE
#433 Clickable Calendar Activities

### LINKED ISSUE #433: Clicking an event in the calendar should show a popup dialog with more information
## Description

With the merger of issue #428, we will have a calendar display of all program activities for the user. However, the activities are not clickable to find out more information such as time range, description, etc.

The expectation is that an MUI Dialog will pop up showing the details of the activity. Clicking a close button or clicking in the shaded area outside of the Dialog will close the dialog. Clicking another activity will show the Dialog but with the details of that activity instead.

## Details and resources

You will need to use the Dialog component from MUI, and you will need to use React state management in order to handle the change of contents of the Dialog and whether or not it's open.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

### PR DESCRIPTION
**Pull request by phoebehala**
## Co-authors:
@veranika-karpava 
@ChainShoe-Z 
@seidior 
@Prabhj33t 
@daveytech 
@phoebehala 

## Proposed changes
This resolves #433 by:
- All activities on the calendar are clickable and can be closed by clicking a close button or clicking in the shaded area outside of the Dialog.
- When users clicked the activity on the calendar, it shows up an activity dialog which displays the details of the clicked activity with a 'close' button. 
- The content of an activity dialog displays the title, start/end date and time of the activity.

## Screenshot
image

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

### CODE REVIEW

**Review by wendyyng — APPROVED** [review]
- After git pull from the branch, I ran `docker compose down` && `docker compose build --no-cache` && `docker-compose up`
- Running `yarn delint` didn't fix any formatting, which indicates that the formatting is in good shape
- Imports are separated and grouped correctly (packages, helper/types, components)
- Hovering over the activity blocks on the calendar changes the arrow cursor to a hand pointer, which indicates to the users that the activities are clickable (except the agenda view, not sure if we can fix this because we're using the package) 
- The activities on the calendar are clickable in all views (month, week, day, agenda)
- After clicking an activity, an activity dialog shows up in the middle of the screen and displays the details of the activity correctly (title, start/end time and description)
- Clicking close button or the shaded area closes the dialog
- After selecting another program in the program picker, the calendar is filled with the selected program's activities
I approve this PR as everything works as expected. Great job everyone!

**Comment by wendyyng** [comment]
A few things that I noticed:
- Sometimes the activity blocks don't have enough space for showing the whole title
Capture
- Hovering over the activities in agenda view changes the mouse cursor to text cursor instead of a hand pointer
- `react-big-calendar` does offer support to show more in month view via a popup. So maybe it's something that we can work on. Documentation: http://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/examples--example-6
- Responsiveness of the programs page: we might want to adjust the size of the 'Program Activities' text and the program picker
- Probably a low priority for now, but I was wondering if we can change colour of the activities. I looked at their documentation and it seems like they only use one colour

**Review by seidior — APPROVED** [review]
Leaving an approval so that we can push through the PR and close out the sprint. I trust Wendy's thorough testing, in combination with Veranika and Phoebe's look throughs.

**Comment by seidior** [comment]
@wendyyng Very thorough beta testing, thanks! All great items to tackle and talk about Monday :)

**Pull request merged**
