### PR TITLE
#448 add all day label to the calendar

### PR DESCRIPTION
**Pull request by SanazDn**
## Proposed changes
Added "All Day" label to the week/day's view first row on the left.

Screen Shot 2022-11-30 at 1 02 40 PM

Screen Shot 2022-11-30 at 1 02 48 PM

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

### CODE REVIEW

**Review by wendyyng — APPROVED** [review]
I approve this PR as the changes appear as expected. 
Not required by the issue but I'm just wondering if the all day label can be capitalized in agenda view as well? Personally I think it'd look a little better.
image

**Comment by SanazDn** [comment]
@wendyyng If we want to change all day in the screenshot that you sent(agenda's view), we should release new issues because those codes do not relate to all day in agenda's view. The code belongs to week/day's view.

**Comment by rrabinovitch** [comment]
changes display as expected on my machine. I agree with @wendyyng 's suggestion re: capitalizing the "all day" text in the agenda view as well.

**Review by camianderson — APPROVED** [review]
The changes display as expected on my machine. 
I am approving the changes.

**Comment by seidior** [comment]
Everything here appears as it should be, and there aren't any unintended side effects. I'm so glad you were able to find a simple, straightforward solution!

I'm not disapproving of the pull request, but I'd love for you to hold off merging until tomorrow morning where the team can talk about this change together. Given that we found an easy, customizable solution, perhaps we can take a couple of iterative passes for the design of this?

I compared the rendered appearance of this header with two sources: the structured, rendered code that `react-big-calendar` uses, and Calendar.app on my Mac. I adapted the structure to see if we can make this heading place in the same area as other elements and to have relatively less visual 'weight', since it's a purely presentational label.

I'm attaching two screenshots below: one of the version that you've created, and one that takes an iterative pass at the design of the element.

sanaz_version
spencer_version

Now, I'm not saying mine is _better_ or that we shouldn't go with your proposed solution; after all, you've already received two approvals from the rest of the team! But given that we still have plenty of time left to deliver the overall feature, this may be the best opportunity to tweak the design a bit.

I'm attaching the horrible, awful code I used to generate my display, in case you want to adapt it in one of your design iterations. Please don't use it; there are probably unneeded classes and better ways of doing certain things. But in case I'm unavailable and you'd like it for reference:

```typescript
  const TimeGutter = () => (
    <>
      <div className="rbc-row rbc-time-header-cell"></div>
      <div className="rbc-allday-cell rbc-time-gutter">
        <div className="rbc-row-content" role="row">
          <div className="rbc-time-slot">
            <span className="rbc-label" style={{ opacity: 0.5 }}>
              all-day
            </span>
          </div>
          <div className="rbc-row"></div>
        </div>
      </div>
    </>
  );
```

One final minor note: I used "all-day" instead of "All Day" since that's what Calendar.app uses. No idea what Google Calendar uses or if we want to mimic their design choices at all. I'm only sharing this so that I can share my process and thinking, not as a correction.

**Pull request merged**
