### PR TITLE
393 ESLint config changes

### PR DESCRIPTION
**Pull request by Nazanin-Rezaei**
## Proposed changes

#393 ESLint config changes
The linter checks the files based on the formatting standards which considered the camelCase for variables and a new line at end of files.
image

## Checklist
- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?

### CODE REVIEW

**Comment by achichikalova** [comment]
@daveytech Thanks for bringing it up. Done.

**Comment by tenzinlekphell** [comment]
Looks good if it's working. Could you explain what `prefer-destructuring: error` and `camelcase: error` means?

**Comment by achichikalova** [comment]
@tenzinlekphell 
Sure, amazing question. 
If explaining it in human language, I would say that camelcase: "error" sets eslint rules to check if variable names are in camelcase. About prefer-destructuring: "error" is requiring destructuring from arrays and/or objects. 
Here are the helpful links:
https://eslint.org/docs/latest/rules/camelcase
https://eslint.org/docs/latest/rules/prefer-destructuring

**Review by daveytech — APPROVED** [review]
Awesome thanks for that change!

**Review by tenzinlekphell — APPROVED** [review]

**Pull request merged**
