### PR TITLE
#419 Add react-big-calendar

### PR DESCRIPTION
**Pull request by seidior**
## Proposed changes

This adds [react-big-calendar](https://github.com/jquense/react-big-calendar) and its TypeScript dependency [@types/react-big-calendar](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-big-calendar) to resolve issue #419. This also updates the caniuse-lite database for webapp since that needed to be done anyway and that's in the same file.

Tested on local and in Docker to ensure no breakage. `yarn delint` and `yarn test` were also performed.

Discussed with the cohort the differences between react-big-calendar and the originally intended package, [react-mui-scheduler](https://www.npmjs.com/package/react-mui-scheduler), and why it wasn't a good fit for us. This was approved by the rest of the team this morning.

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?

### CODE REVIEW

**Review by daveytech — APPROVED** [review]
Thank you for the research about which package would be best to use based on community size and activity. Good to merge!

**Comment by camianderson** [comment]
Great job adding the new calendar package!

**Review by camianderson — APPROVED** [review]
Thank you for adding the new calendar! I am approving it so you can merge it.

**Review by rrabinovitch — APPROVED** [review]
Thanks for the group discussion on what to consider when choosing packages.

No issues or breakages occurred when rebuilding my docker container, running `yarn install`, and running the linter and tests with the addition of this package 👍

**Comment by seidior** [comment]
Thank you everyone for the reviews! Merging this into main now.

**Pull request merged**
