### PR TITLE
Swap prod secrets from environment variables to Docker secrets

### LINKED ISSUE #308: The api still requires secrets to be passed via env vars in prod
## Expected behaviour

The api service gets secrets from Docker secrets in production instead of from environment variables.

## Actual behaviour

In order to deploy the api service, all the secrets need to be loaded into environment variables, which is an unnecessary additional step in deployment, and less secure than using Docker secrets.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

### PR DESCRIPTION
**Pull request by davidvandusen**
## Proposed changes

Takes the environment variables that the production api service was using that contain secret values and configures them to be read from Docker secrets instead. 

Resolves #308.

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

### CODE REVIEW

**Comment by BRashad** [comment]
Is this the best practice to when Docker is being used in the project we change the environment variables and configure them to be read from Docker? 
I wonder why this is done at this stage of the project, not for example later or earlier? Any best practice on when is the best time to do such changes?

**Comment by davidvandusen** [comment]
@BRashad This ticket is part of a larger project to implement continuous deployment. I think the conversation about best practices isn't relevant to discuss on this PR since all it does is build on many incremental steps that have already been done and precedes more incremental work that is coming up.

If you want to learn about Docker secrets to see get an idea of why they're being used, a good start is the [Docker secrets docs](https://docs.docker.com/engine/swarm/secrets/).

**Comment by BRashad** [comment]
ok no more questions then.

**Review by BRashad — APPROVED** [review]

**Review by eileenxue — APPROVED** [review]
Looks good to me. So many secrets, better security. Would be interested in reviewing the Docker Secrets page you provided in an earlier comment. Thanks!

**Pull request merged**
