### PR TITLE
345 add profile icon with route

### PR DESCRIPTION
**Pull request by achichikalova**
## Proposed changes
This PR addresses issue #345.
Add a route for the profile, add an icon to the navbar, and add a home link to the logo.

## Screenshot
image

## Checklist
- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

### CODE REVIEW

**Review by seidior — APPROVED** [review]
I was present for the creation of these commits. This pull request seems to satisfy the goals set out in the issue and resolves issue #345. More work will need to be done for styling, but the placeholder content works well for now. No extraneous files were added as part of this commit.

**Comment by SiriusLL** [comment]
This meets all requirements in the checklist.

**Comment by tenzinlekphell** [comment]
Requirements Met: 
- Profile Icon on the right hand corner
- a route that links the profile button to the profile page
- a home link button called Rhizone

Completed!

**Review by denizedaza — APPROVED** [review]
Requirements met in the issue.

**Pull request merged**
