### PR TITLE
#416 Add home page link to the Rhizone logo in the Navbar

### LINKED ISSUE #416: The Rhizone logo should link to homepage
## Expected behaviour

When clicking on the Rhizone logo in the top left corner, the user should be redirected to the home page

## Actual behaviour

No link is attached to component.

## Checklist

- [x] This issue is linked to the appropriate project.
- [x] This issue has appropriate labels.

### PR DESCRIPTION
**Pull request by Prabhj33t**
## Proposed changes

This pull request resolves #416 . It adds the homepage link to the 'Rhizone' logo in the navbar. Users will now be redirected to the home page when they click the 'Rhizone' logo. Style is added to the Link tag that wraps the 'Rhizone' logo so that the original style of the 'Rhizone' logo is not affected by the default style of Link. As a result, the UI is unchanged.

416-Screenshot

## Checklist

- [x] Are the issues being addressed linked to this PR?
- [x] Do all commit messages start with the issue number?
- [x] Are all code changes sufficiently tested?
- [x] Are there screenshots for UI changes?

### CODE REVIEW

**Comment by seidior** [comment]
Closing this for now to give the team a chance to re-file the pull request with the reviewed procedures.

**Comment by wendyyng** [comment]
Updates for this ticket:

- Style for the Link that wraps the Rhizone logo was added so that the original style was unaffected by the default Link style
- Imports from libraries and components have been separated by an empty line
- "Yarn delint" was run for checking and fixing formatting
- In a previous commit, 'Calendar' component was pushed - which has now been removed since it is not related to the issue
- Commits from the main branch have also been merged to this branch #416

**Review by seidior — APPROVED** [review]
I checked out the code on my development machine, recreated the Docker containers, brought the containers up, and tested it out.

The functionality seems to match the description of the changes, with clicking the header link returning you to the homepage as expected. No UI changes are observed, and the code appears to conform to code style guidelines.

All automated tests pass without error, and `yarn delint` did not modify any files or show any errors. I approve of this pull request.

**Review by veranika-karpava — APPROVED** [review]
The  homepage link to the 'Rhizone' logo in the navbar works correctly in my local machine. It redirects to the homepage.  Great work!

**Pull request merged**
